import {ApiProperty} from '@nestjs/swagger';

export class LoginByAuthTokenDto {
  @ApiProperty({
    type: String,
    description: 'Токен',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhVmFsdWVzIjp7InRlbGVncmFtSWQiOiJmajM0Z3l1dHJnZmRoajQzNCIsImZpcnN0TmFtZSI6IlZsYWRpbWlyIiwibGFzdE5hbWUiOiJJdmFub3YiLCJ1c2VyTmFtZSI6Iml2YXZsZWciLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTE2VDE1OjU0OjQ3LjM1NVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTE2VDE1OjU0OjQ3LjM1NVoifSwiX3ByZXZpb3VzRGF0YVZhbHVlcyI6eyJ0ZWxlZ3JhbUlkIjoiZmozNGd5dXRyZ2ZkaGo0MzQiLCJmaXJzdE5hbWUiOiJWbGFkaW1pciIsImxhc3ROYW1lIjoiSXZhbm92IiwidXNlck5hbWUiOiJpdmF2bGVnIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xNlQxNTo1NDo0Ny4zNTVaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xNlQxNTo1NDo0Ny4zNTVaIn0sInVuaXFubyI6MSwiX2NoYW5nZWQiOnt9LCJfb3B0aW9ucyI6eyJpc05ld1JlY29yZCI6ZmFsc2UsIl9zY2hlbWEiOm51bGwsIl9zY2hlbWFEZWxpbWl0ZXIiOiIiLCJpbmNsdWRlVmFsaWRhdGVkIjp0cnVlLCJyYXciOnRydWV9LCJpc05ld1JlY29yZCI6ZmFsc2UsImlhdCI6MTY2NTkzNzU4MCwiZXhwIjoxNjY1OTQxMTgwfQ.bLlXEB68u0LqgNxFGb_t9Ch3-8GM1K-FOfIbjWiJA20',
    required: true,
  })
  readonly token: string;
}
